### ISSUE TITLE
Fly-Pie settings crash after a few seconds

### ISSUE THREAD

**Issue by l-fura** [Schneegans/Fly-Pie#331] opened 2023-11-14 11:35 UTC
## Describe the Bug
Fly-Pie settings crash after a few seconds. 

1. Go to Settings
2. After a few seconds Fly-Pie crashes

After 
journalctl -f -o cat | grep -E 'flypie|' and starting the Fly-Pie I received this:

```
`Started GNOME Terminal Server.
Started VTE child process 305980 launched by gnome-terminal-server process 305958.
[session uid=1000 pid=2038] Activating service name='org.gnome.Shell.Extensions' requested by ':1.787' (uid=1000 pid=306213 comm="gnome-extensions prefs flypie@schneegans.github.co")
Started Application launched by gnome-shell.
[session uid=1000 pid=2038] Successfully activated service 'org.gnome.Shell.Extensions'
[system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.209653' (uid=1000 pid=306219 comm="/usr/bin/gjs /usr/share/gnome-shell/org.gnome.Shel")
Starting Hostname Service...
[system] Successfully activated service 'org.freedesktop.hostname1'
Started Hostname Service.
Can't update stage views actor <unnamed>[<ClutterActor>:0x55c2f068dc50] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x55c2f068ccb0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x55c2f068dc50] is on because it needs an allocation.
pool-org.gnome.[306246]: segfault at 18 ip 00007ff6ebb75ae3 sp 00007ff6a37fd9d8 error 6 in libglib-2.0.so.0.7200.4[7ff6ebb1e000+8f000] likely on CPU 6 (core 3, socket 0)
Code: 2b 45 0c 00 4a 8d 0c c1 48 39 11 0f 84 96 00 00 00 e9 d1 92 fa ff 90 c3 0f 1f 80 00 00 00 00 48 8b 4a 18 48 8b 72 10 45 89 c1 <48> 89 4e 18 48 89 71 10 48 8b 0d f6 44 0c 00 4e 8d 14 c9 49 8b 0a
Can't update stage views actor <dashtodockContainer>[<Gjs_ubuntu-dock_ubuntu_com_docking_DashToDock>:0x55c2ec3ae0a0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<Gjs_ubuntu-dock_ubuntu_com_docking_DashSlideContainer>:0x55c2edeb4bc0] is on because it needs an allocation.
Can't update stage views actor <dashtodockBox>[<StBoxLayout>:0x55c2ede247e0] is on because it needs an allocation.
Can't update stage views actor <dash>[<Gjs_ubuntu-dock_ubuntu_com_dash_DockDash>:0x55c2f9127bc0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StWidget>:0x55c2ef842120] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x55c2f02dcc90] is on because it needs an allocation.
Can't update stage views actor <dashtodockDashContainer>[<StBoxLayout>:0x55c2f40dcfb0] is on because it needs an allocation.
Can't update stage views actor <dashtodockDashScrollview>[<StScrollView>:0x55c2eeeb1290] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StBoxLayout>:0x55c2ed503c50] is on because it needs an allocation.
Can't update stage views actor <dashtodockContainer>[<Gjs_ubuntu-dock_ubuntu_com_docking_DashToDock>:0x55c2ec3ae0a0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<Gjs_ubuntu-dock_ubuntu_com_docking_DashSlideContainer>:0x55c2edeb4bc0] is on because it needs an allocation.
Can't update stage views actor <dashtodockBox>[<StBoxLayout>:0x55c2ede247e0] is on because it needs an allocation.
Can't update stage views actor <dash>[<Gjs_ubuntu-dock_ubuntu_com_dash_DockDash>:0x55c2f9127bc0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StWidget>:0x55c2ef842120] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x55c2f02dcc90] is on because it needs an allocation.
Can't update stage views actor <dashtodockDashContainer>[<StBoxLayout>:0x55c2f40dcfb0] is on because it needs an allocation.
Can't update stage views actor <dashtodockDashScrollview>[<StScrollView>:0x55c2eeeb1290] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StBoxLayout>:0x55c2ed503c50] is on because it needs an allocation.
Can't update stage views actor <dashtodockContainer>[<Gjs_ubuntu-dock_ubuntu_com_docking_DashToDock>:0x55c2ec3ae0a0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<Gjs_ubuntu-dock_ubuntu_com_docking_DashSlideContainer>:0x55c2edeb4bc0] is on because it needs an allocation.
Can't update stage views actor <dashtodockBox>[<StBoxLayout>:0x55c2ede247e0] is on because it needs an allocation.
Can't update stage views actor <dash>[<Gjs_ubuntu-dock_ubuntu_com_dash_DockDash>:0x55c2f9127bc0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StWidget>:0x55c2ef842120] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x55c2f02dcc90] is on because it needs an allocation.
Can't update stage views actor <dashtodockDashContainer>[<StBoxLayout>:0x55c2f40dcfb0] is on because it needs an allocation.
Can't update stage views actor <dashtodockDashScrollview>[<StScrollView>:0x55c2eeeb1290] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StBoxLayout>:0x55c2ed503c50] is on because it needs an allocation.
Can't update stage views actor <dashtodockContainer>[<Gjs_ubuntu-dock_ubuntu_com_docking_DashToDock>:0x55c2ec3ae0a0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<Gjs_ubuntu-dock_ubuntu_com_docking_DashSlideContainer>:0x55c2edeb4bc0] is on because it needs an allocation.
Can't update stage views actor <dashtodockBox>[<StBoxLayout>:0x55c2ede247e0] is on because it needs an allocation.
Can't update stage views actor <dash>[<Gjs_ubuntu-dock_ubuntu_com_dash_DockDash>:0x55c2f9127bc0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StWidget>:0x55c2ef842120] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x55c2f02dcc90] is on because it needs an allocation.
Can't update stage views actor <dashtodockDashContainer>[<StBoxLayout>:0x55c2f40dcfb0] is on because it needs an allocation.
Can't update stage views actor <dashtodockDashScrollview>[<StScrollView>:0x55c2eeeb1290] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StBoxLayout>:0x55c2ed503c50] is on because it needs an allocation.
Can't update stage views actor <dashtodockContainer>[<Gjs_ubuntu-dock_ubuntu_com_docking_DashToDock>:0x55c2ec3ae0a0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<Gjs_ubuntu-dock_ubuntu_com_docking_DashSlideContainer>:0x55c2edeb4bc0] is on because it needs an allocation.
Can't update stage views actor <dashtodockBox>[<StBoxLayout>:0x55c2ede247e0] is on because it needs an allocation.
Can't update stage views actor <dash>[<Gjs_ubuntu-dock_ubuntu_com_dash_DockDash>:0x55c2f9127bc0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StWidget>:0x55c2ef842120] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x55c2f02dcc90] is on because it needs an allocation.
Can't update stage views actor <dashtodockDashContainer>[<StBoxLayout>:0x55c2f40dcfb0] is on because it needs an allocation.
Can't update stage views actor <dashtodockDashScrollview>[<StScrollView>:0x55c2eeeb1290] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StBoxLayout>:0x55c2ed503c50] is on because it needs an allocation.
Can't update stage views actor <dashtodockContainer>[<Gjs_ubuntu-dock_ubuntu_com_docking_DashToDock>:0x55c2ec3ae0a0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<Gjs_ubuntu-dock_ubuntu_com_docking_DashSlideContainer>:0x55c2edeb4bc0] is on because it needs an allocation.
Can't update stage views actor <dashtodockBox>[<StBoxLayout>:0x55c2ede247e0] is on because it needs an allocation.
Can't update stage views actor <dash>[<Gjs_ubuntu-dock_ubuntu_com_dash_DockDash>:0x55c2f9127bc0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StWidget>:0x55c2ef842120] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x55c2f02dcc90] is on because it needs an allocation.
Can't update stage views actor <dashtodockDashContainer>[<StBoxLayout>:0x55c2f40dcfb0] is on because it needs an allocation.
Can't update stage views actor <dashtodockDashScrollview>[<StScrollView>:0x55c2eeeb1290] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StBoxLayout>:0x55c2ed503c50] is on because it needs an allocation.
`
## Expected Behavior
Not crashing

## System
_Please complete the following information:_
 - Linux distribution - Ubuntu 22.04
 - Fly-Pie version Fly-Pie 22
 - GNOME Shell version: 42.9

**Comment by Schneegans** [comment] 2023-11-14 11:51
Hi there! Thanks for the report, but this is most likely duplicate of #313. Maybe you could add your system details there?

**Closed by Schneegans** 2023-11-14 11:51 UTC
Labels: bug
