### ISSUE TITLE
FlyPie - GNOME 45 Support

### ISSUE THREAD

**Issue by D3vil0p3r** [Schneegans/Fly-Pie#317] opened 2023-08-29 19:14 UTC
Hello @Schneegans ! In September GNOME 45 will be released (currently it is available as beta). FlyPie will support GNOME 45?

**Comment by Schneegans** [comment] 2023-08-30 05:32
Hi there! Yes, I am working on it in the `feature/esm-modules` branch. I can not promise that it will be done when GNOME 45 is released because _it is a hell of work_ :sweat_smile:. But I am pretty confident that there is no reason why it shouldn't work.

I already ported the Desktop Cube and Burn-My-Windows. I haven't merged the branches there yet, but you can get an idea about the required work (diffs are [here](https://github.com/Schneegans/Burn-My-Windows/pull/373/files) and [there](https://github.com/Schneegans/Desktop-Cube/pull/132/files)). And Fly-Pie is by far the most complex of my extensions...

**Comment by Schneegans** [comment] 2023-09-05 05:53
Do you have GNOME 45 already running on real hardware? I think that the port is already running quite well, but it's hard to test everything in a virtual machine. Else I'll just release an initial version for GNOME 45 and wait for user feedback :wink:

**Comment by D3vil0p3r** [comment] 2023-09-05 06:05
No but I can setup this afternoon a GNOME 45 on real hw. What do you need in particular?

**Comment by Schneegans** [comment] 2023-09-05 06:09
Well, I cannot properly test touch- and stylus input, multi-cursor input under Wayland as well as display scaling (HiDPI stuff). And besides this, it's maybe helpful if somebody else just plays around a bit. For instance, I just noticed by chance that the achievement notifications were not working at all. Maybe there are similar issues hidden :smile: .

**Comment by D3vil0p3r** [comment] 2023-09-05 06:22
Uhm so I need a touch screen?

**Comment by Schneegans** [comment] 2023-09-05 06:41
No, just test what you can. It would be cool if you could test the display scaling. Especially the fractional scaling on X11 and Wayland.

**Comment by D3vil0p3r** [comment] 2023-09-05 06:44
How can I test stylus input and multi-cursor input?

**Comment by Schneegans** [comment] 2023-09-05 07:29
I think you could only test it if you had some kind of Wacom tablet or convertible notebook with pen input.

**Closed** 2023-09-09 10:41 UTC

**Comment by Schneegans** [comment] 2023-09-09 10:44
I just merged the GNOME 45 support into `main`. I think I'll release an initial version today so that early adopters can test for any bugs. If something does not work as intended, we can fix it :wink:. I think that all the basic functionality should be working.

**Comment by D3vil0p3r** [comment] 2023-09-09 11:23
Thank you very much

**Comment by D3vil0p3r** [comment] 2023-10-05 10:57
Hello @Schneegans On Arch Linux now GNOME 45 is inside the `gnome-unstable` repository before to be migrated to `Extra` repository.

For testing, I used the `gnome-unstable` repository to upgrade my GNOME environment, and after reboot, when I checked the extension list, I noted that on FlyPie extension I get the message:
```
GLib.FileError: Failed to open file “/usr/share/gnome-shell/extensions/flypie@schneegans.github.com/schemas/gschemas.compiled”: open() failed: No such file or directory
```
Indeed, inside `/usr/share/gnome-shell/extensions/flypie@schneegans.github.com/schemas/` folder, I don't have `gschemas.compiled` file.

**Comment by Schneegans** [comment] 2023-10-05 11:45
Hi @D3vil0p3r! I think that this is an issue with the packaging. Since GNOME 45, these compiled schema files are not to be distributed anymore with the extensions as they are somewhat platform-dependent. They are rather generated on-the-fly when the extension is installed with `gnome-extensions install <zip file>`. The AUR package does not use `gnome-extensions install <zip file>`, so the compiled schema file is not generated.

So either the AUR package should use `gnome-extensions install <zip file>` instead of a manual install, or you would need to compile the schemas manually afterwards. This should be possible with something along the lines of 

```
sudo glib-compile-schemas /usr/share/gnome-shell/extensions/flypie@schneegans.github.com/schemas/
```

**Comment by D3vil0p3r** [comment] 2023-10-05 11:53
Yes, indeed I tested with the following PKGBUILD:
```
# Maintainer: Igor Dyatlov <dyatlov.igor@protonmail.com>

pkgname=gnome-shell-extension-fly-pie-git
pkgver=24.r5.gac9d535
pkgrel=1
pkgdesc="Fly-Pie is an innovative marking menu written as a GNOME Shell extension"
arch=('any')
url="https://github.com/Schneegans/Fly-Pie"
license=('MIT')
depends=('gnome-shell')
makedepends=('git' 'zip')
provides=("${pkgname%-git}")
conflicts=("${pkgname%-git}")
source=(${pkgname%-git}::git+$url.git)
sha256sums=('SKIP')

pkgver() {
  cd "${pkgname%-git}"
  git describe --long --tags | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g'
}

build() {
  cd "${pkgname%-git}"
  
  make zip
}

package() {
  cd "${pkgname%-git}"
  _uuid='flypie@schneegans.github.com'
  install -d "$pkgdir/usr/share/gnome-shell/extensions/$_uuid"
  bsdtar -xvf $_uuid.zip -C "$pkgdir/usr/share/gnome-shell/extensions/$_uuid"
  glib-compile-schemas "$pkgdir/usr/share/gnome-shell/extensions/$_uuid/schemas"
}
```
and it works.

I hope that the maintainer can update it. I left a comment under the AUR package but the maintainer last login is on August. I created an Orphan request so, if accepted, I can manage directly the AUR package and fix the issue.
